### ISSUE TITLE
Cannot send max coins or larger amount with Iphone app

### ISSUE THREAD

**Issue by ohcee** [steel97/veil_wallet#11] opened 2023-12-14 19:51 UTC
**Describe the bug**
When trying to send the max amount out of the wallet the transaction fails. I have tried with subtract fee while sending from amount on and off. I tried different amounts lower but nothing worked until much a lower (see very bottom photo)coin amount.

**To Reproduce**
1. Go to main screen
2. Click on send icon button
3. Enter address of recipient
4. Enter total number of coins ( with/without .decimal and with/without subtract fee from amount enabled)
5. Press Next
6. Confirm transaction and press Send
7. Error occurs

**Expected behavior**
The expected behavior is to make the transaction successful to send the max coins or close to the max out of the wallet.

**Screenshots**

![IMG_8D49F1AF57B3-1](https://github.com/steel97/veil_wallet/assets/46406370/9f3bb4eb-559b-494f-af87-436ba823ec3f)
![IMG_0D0D97B5E1D5-1](https://github.com/steel97/veil_wallet/assets/46406370/1ed51d73-6395-4e98-8ad4-0914bee91faa)

**Smartphone**
 - Device: iPhone11
 - OS: iOS 17.2

**Additional context**
I was able to send a smaller transactions but never able to send the full amount. After the smaller amount was sent I was still unable to send the remaining full amount. 
![IMG_0905](https://github.com/steel97/veil_wallet/assets/46406370/d08090ba-4254-42cf-be99-2799bcee58a8)

I have switch the node from US 1to EU 2 to see if this may fix it and I will test again after the transactions load.

**Comment by steel97** [comment] 2023-12-15 10:55
Thanks for bug report! I afraid this might be specific to your address (something wrong with UTXO to keyimage mapping). I was unable to reproduce this issue, however will check for possible solutions.
Could you please check if issue happens with another address?

**Comment by steel97** [comment] 2023-12-15 12:29
Please try latest actions build, it should show more debug info when send fails

**Comment by ohcee** [comment] 2023-12-15 14:24
I will test the updated version and try another address shortly. I will update after.

**Comment by ohcee** [comment] 2023-12-15 17:01
Update:

So I have been testing back and forth with my linux wallet and iphone wallet. (Maybe a testnet option would be helpful for testing purposes) I tried to send to send the full amount from the linux wallet to a new address on my iphone wallet and got this error.
![Screenshot from 2023-12-15 08-51-21](https://github.com/steel97/veil_wallet/assets/46406370/201fa7e5-1b44-4680-8fc8-2d2f788bba01)

I then tried to send the remaining amount from my iPhone to the linux wallet and got this error. 
![IMG_1E289C14165B-1](https://github.com/steel97/veil_wallet/assets/46406370/bd914475-bcde-4e40-af23-3d18e20484f0)

**Comment by steel97** [comment] 2023-12-15 19:22
@ohcee hmm, interesting... I made some changes, `verify-commit-tally-failed` might be fixed now (I think I had this error previously with web-wallet, I applied same fix to mobile wallet).
`bad-anonin-dup-i` means duplicate ringct index, for real outputs code make checks for duplicated indexes, but for some reason it still included in transaction (maybe fake anon outputs had same index, or serialization works not as expected).
For this issue I also added some more debug info and additional checks.
Please check latest build from actions tab

**Comment by ohcee** [comment] 2023-12-15 22:19
@steel97 Good news is that the Linux wallet had no issues this time sending everything. It worked this time. The iphone wallet now has the same error message (as above) as the linux wallet before with the `(verify-commit-tally-failed(code 16))`with "Subtract fee from amount" on or off. It gives the same error.

**Closed** 2023-12-16 01:12 UTC
Labels: bug

**Comment by steel97** [comment] 2023-12-16 06:53
I also just added send max button (icon on the right side of amount input field)

**Comment by ohcee** [comment] 2023-12-16 14:13
Nice work on the max button. Testing it now. 

Works on both iphone and linux.

**Comment by steel97** [comment] 2023-12-16 16:41
Some notes: `send all balance` button actually inserts **available balance** (if you have some unconfirmed coins they will be not counted until they confirmed by blockchain)

**Comment by ohcee** [comment] 2023-12-17 16:03
One thing to add is when you use the send max button. The slider for `Subtract fee from amount` should be slid to on or the is no way to pay for the transaction fee. Currently you have to slide it manually.

**Comment by steel97** [comment] 2023-12-17 17:22
@ohcee done!
